# Site başlığı ve açıklama
title: TurkToken
description: "TurkToken is a modern tokenization and text analysis toolkit for Turkish.
  It combines word-, subword- (BPE/Unigram), and byte-level tokenization with
  Turkish diacritic handling, light morphology-aware heuristics, and Jekyll-based
  visualizations. This site publishes per-author top words, token frequencies,
  and example charts."
lang: tr

# Tema ve eklentiler
theme: minima
plugins:
  - jekyll-seo-tag   # SEO için meta etiketleri
  - jekyll-feed      # RSS feed desteği

# Koleksiyonlar (yazarlar)
collections:
  yazarlar:                # _yazarlar/ klasöründeki dosyaları işler
    output: true            # HTML çıktısı üret
    permalink: /yazar/:name/ # URL yapısı -> /yazar/ahmet-umit/

# Varsayılan değerler (default ayarlar)
defaults:
  - scope:
      path: ""              # tüm dosyalar için geçerli
      type: "yazarlar"      # sadece yazar koleksiyonu
    values:
      layout: yazar         # varsayılan layout = yazar.html

# Link yapısı
permalink: pretty           # /sayfa/ şeklinde temiz URL’ler

# Markdown ayarları
markdown: kramdown
kramdown:
  input: GFM                # GitHub-Flavored Markdown desteği
